package logic.model

enum class ActionType {
    // Project-related actions
    PROJECT_CREATED,
    PROJECT_TITLE_MODIFIED,
    PROJECT_ASSIGNED_USER,
    PROJECT_UNASSIGNED_USER,
    PROJECT_DELETED,

    // Task-related actions
    TASK_CREATED,
    TASK_TITLE_MODIFIED,
    TASK_DESCRIPTION_MODIFIED,
    TASK_ASSIGNED_USER_MODIFIED,
    TASK_STATE_CHANGED,
    TASK_DELETED
}
